defaults: &defaults
    adapter: mysql2
    pool: 5
    timeout: 5000
    username: root
    host: localhost
    encoding: utf8
    collation: utf8_unicode_ci

development:
    database: pwr_development
    <<: *defaults

test:
    database: pwr_test
    <<: *defaults

production:
    database: pwr_production
    <<: *defaults